bind-key c new-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"

# 配色
set -g default-terminal "xterm-256color"

# 前缀键 ctrl+b 重定向到 ctrl+]
unbind C-b
set-option -g prefix C-]
bind C-] send-prefix

# 启用鼠标(Tmux v2.1)
set -g mouse on
